
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: |
    sudo apt-get update -qq -y

    sudo apt-get install gem -qq -y
    echo -n "Gem : "
    gem --version

    sudo gem install r10k -v 2.6.4
    r10k version

    sudo apt-get install puppet -qq -y
    echo -n "Puppet: "
    puppet --version

    wget -nv https://apt.puppetlabs.com/puppet5-release-xenial.deb
    sudo dpkg -i puppet5-release-xenial.deb
    sudo apt-get install -qq -f
    sudo rm -f puppet5-release-xenial.deb

    echo "******** point 0 ********"
    git clone -b ubuntu16 https://github.com/StuartWheater/datashield-infrastructure.git datashield-infrastructure
    pushd datashield-infrastructure/puppet/environments/datashield_travis && sudo r10k puppetfile install && popd
    sudo puppet apply datashield-infrastructure/puppet/environments/datashield_travis/manifests/site.pp --environment datashield_travis --environmentpath datashield-infrastructure/puppet/environments
  displayName: 'Install'

- bash: |
    R CMD check
  displayName: 'Test'
