
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: |
    sudo apt-get install -qq curl -y
    curl -L -o /tmp/travis-tool.sh http://raw.github.com/StuartWheater/r-travis/master/scripts/travis-tool.sh
    chmod 755 /tmp/travis-tool.sh
    wget -nv https://apt.puppetlabs.com/puppet5-release-xenial.deb
    sudo dpkg -i puppet5-release-xenial.deb
    sudo apt-get install -qq -f
    sudo rm -f puppet5-release-xenial.deb
    sudo apt-get update -qq
    sudo apt-get install -qq puppet-agent -y
    sudo apt-get install -qq git -y
    sudo apt-get install -qq rudy -y
    sudo /opt/puppetlabs/puppet/bin/gem install r10k -v 2.6.4
    git clone -b ubuntu16 https://github.com/StuartWheater/datashield-infrastructure.git /tmp/datashield-infrastructure
  displayName: 'Before Install'
  
- script: |
    cd /tmp/datashield-infrastructure/puppet/environments/datashield_travis && sudo /opt/puppetlabs/puppet/bin/r10k puppetfile install && cd --
    sudo /opt/puppetlabs/bin/puppet apply /tmp/datashield-infrastructure/puppet/environments/datashield_travis/manifests/site.pp --environment datashield_travis --environmentpath /tmp/datashield-infrastructure/puppet/environments
  displayName: 'Install'
