
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: |
    sudo apt-get clean all
    sudo apt-get update
    sudo apt-get upgrade -y
    sudo apt-get dist-upgrade -y
    sudo apt-get autoremove -y
    sudo apt-get clean all

    wget -nv https://apt.puppetlabs.com/puppet5-release-xenial.deb
    sudo dpkg -i puppet5-release-xenial.deb
    sudo apt-get install -qq -f
    sudo rm -f puppet5-release-xenial.deb
    sudo apt-get puppet-agent -y

    sudo /opt/puppetlabs/puppet/bin/gem install r10k

    echo -n "Puppet version: "
    /opt/puppetlabs/bin/puppet --version
    /opt/puppetlabs/puppet/bin/r10k version

    git clone -b ubuntu16 https://github.com/StuartWheater/datashield-infrastructure.git datashield-infrastructure
    pushd datashield-infrastructure/puppet/environments/datashield_travis && sudo /opt/puppetlabs/puppet/bin/r10k puppetfile install && popd
    sudo /opt/puppetlabs/bin/puppet apply --verbose datashield-infrastructure/puppet/environments/datashield_travis/manifests/site.pp --environment datashield_travis --environmentpath datashield-infrastructure/puppet/environments || true

    echo "========"
    sudo cat /opt/puppetlabs/puppet/cache/state/state.yaml
    echo "========"

    sudo mysql --user=root --password='' --execute="SHOW databases"
    sudo mysql --user=root --password=rootpass --execute="SHOW databases"
  displayName: 'Install'

- bash: |
    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
    sudo add-apt-repository 'deb [arch=amd64,i386] https://cran.rstudio.com/bin/linux/ubuntu xenial/'
    sudo apt-get update
    sudo apt-get install -qq r-base -y
  displayName: 'Install R'

- bash: |
    R CMD check
  displayName: 'Test'
