
pool:
  vmImage: 'Ubuntu 16.04'

steps:
- bash: |
    wget -nv https://apt.puppetlabs.com/puppet5-release-xenial.deb
    sudo dpkg -i puppet5-release-xenial.deb
    sudo apt-get install -qq -f
    sudo rm -f puppet5-release-xenial.deb
    sudo apt-get update -qq
    sudo apt-get install -qq rudy -y
    sudo apt-get install -qq puppet-agent -y
    sudo apt-get install -qq git -y
    sudo /opt/puppetlabs/puppet/bin/gem install r10k -v 2.6.4

    echo -n "Puppet version: "
    /opt/puppetlabs/bin/puppet --version
    /opt/puppetlabs/puppet/bin/r10k version

    git clone -b ubuntu16 https://github.com/StuartWheater/datashield-infrastructure.git datashield-infrastructure
    pushd datashield-infrastructure/puppet/environments/datashield_travis && sudo /opt/puppetlabs/puppet/bin/r10k puppetfile install && popd
    sudo /opt/puppetlabs/bin/puppet apply datashield-infrastructure/puppet/environments/datashield_travis/manifests/site.pp --environment datashield_travis --environmentpath datashield-infrastructure/puppet/environments || true

    ls -la ~
    ls -la .
    sudo cat /etc/mysql/my.cnf
  displayName: 'Install'

- bash: |
    R CMD check
  displayName: 'Test'
